# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# source "$HOME/.cargo/env"
# cargo install typos-cli
# typos -c typos.toml
# typos -c typos.toml -w

[default.extend-words]
# don't correct these false positives
ba = "ba"
ned = "ned"